// Single source of truth for IPC channel names.
//
// Main, preload, and renderer all reference values from this map instead of typing the
// channel string literally, so a typo at any site is a compile-time error and a renamed
// channel is a single edit. See CONTEXT.md for the IPC seam vocabulary.
export const CHANNELS = {
  account: {
    get: "account:get",
    update: "account:update",
  },
  app: {
    flushAndQuit: "app:flushAndQuit",
    fullscreenChange: "app:fullscreenChange",
    setMenuBarIconVisible: "app:setMenuBarIconVisible",
    setUnsavedChanges: "app:setUnsavedChanges",
  },
  appSettings: {
    get: "appSettings:get",
    update: "appSettings:update",
  },
  automations: {
    create: "automations:create",
    delete: "automations:delete",
    execute: "automations:execute",
    getAll: "automations:getAll",
    getAvailableActions: "automations:getAvailableActions",
    getById: "automations:getById",
    getRunHistory: "automations:getRunHistory",
    update: "automations:update",
  },
  browser: {
    attach: "browser:attach",
    back: "browser:back",
    deleteCapture: "browser:deleteCapture",
    destroy: "browser:destroy",
    detach: "browser:detach",
    forward: "browser:forward",
    getNavState: "browser:getNavState",
    navState: "browser:navState",
    navigate: "browser:navigate",
    reload: "browser:reload",
    selectModeChanged: "browser:selectModeChanged",
    selection: "browser:selection",
    setBounds: "browser:setBounds",
    setSelectMode: "browser:setSelectMode",
    setVisible: "browser:setVisible",
    stop: "browser:stop",
  },
  connections: {
    checkCredentials: "connections:checkCredentials",
    deleteResource: "connections:deleteResource",
    getAsanaProjects: "connections:getAsanaProjects",
    getByProvider: "connections:getByProvider",
    getGithubRepos: "connections:getGithubRepos",
    getGitlabProjects: "connections:getGitlabProjects",
    getJiraProjects: "connections:getJiraProjects",
    getLinearTeams: "connections:getLinearTeams",
    getSelectedResources: "connections:getSelectedResources",
    getSentryProjects: "connections:getSentryProjects",
    getSocketDevOrganizations: "connections:getSocketDevOrganizations",
    getTrelloBoards: "connections:getTrelloBoards",
    listStates: "connections:listStates",
    removeResource: "connections:removeResource",
    revoke: "connections:revoke",
    saveCredentials: "connections:saveCredentials",
    saveResources: "connections:saveResources",
    updateState: "connections:updateState",
  },
  entities: {
    create: "entities:create",
    delete: "entities:delete",
    getAll: "entities:getAll",
    getById: "entities:getById",
    search: "entities:search",
    update: "entities:update",
  },
  fileExplorer: {
    getPathInfo: "fileExplorer:getPathInfo",
    listDir: "fileExplorer:listDir",
    readDirectory: "fileExplorer:readDirectory",
    readDirectoryShallow: "fileExplorer:readDirectoryShallow",
    readFile: "fileExplorer:readFile",
    readFileText: "fileExplorer:readFileText",
    searchFiles: "fileExplorer:searchFiles",
  },
  git: {
    cloneRepo: "git:cloneRepo",
    createBranch: "git:createBranch",
    createWorktree: "git:createWorktree",
    getBranches: "git:getBranches",
    getCurrentBranch: "git:getCurrentBranch",
    getDiff: "git:getDiff",
    getLog: "git:getLog",
    getRemotes: "git:getRemotes",
    getRepoRoot: "git:getRepoRoot",
    getStatus: "git:getStatus",
    getWorktreesDir: "git:getWorktreesDir",
    importLocalRepo: "git:importLocalRepo",
    importLocalRepoDirect: "git:importLocalRepoDirect",
    initRepo: "git:initRepo",
    isRepo: "git:isRepo",
    removeWorktree: "git:removeWorktree",
    renameBranch: "git:renameBranch",
    resetHard: "git:resetHard",
  },
  guards: {
    checkPackage: "guards:checkPackage",
    checkPackages: "guards:checkPackages",
    getActiveGuard: "guards:getActiveGuard",
    getPackageScore: "guards:getPackageScore",
    scanWorkspace: "guards:scanWorkspace",
  },
  imageProxy: {
    sign: "imageProxy:sign",
  },
  issues: {
    create: "issues:create",
    delete: "issues:delete",
    getAll: "issues:getAll",
    getById: "issues:getById",
    update: "issues:update",
  },
  projects: {
    // ── lifecycle ──
    archive: "projects:archive",
    create: "projects:create",
    delete: "projects:delete",
    findByRemoteOrigin: "projects:findByRemoteOrigin",
    findOrCreate: "projects:findOrCreate",
    get: "projects:get",
    list: "projects:list",
    listByAccount: "projects:listByAccount",
    remove: "projects:remove",
    update: "projects:update",
    // ── resources ──
    addResource: "projects:addResource",
    listAvailableResources: "projects:listAvailableResources",
    listResources: "projects:listResources",
    removeResource: "projects:removeResource",
    // ── issues (via linked resources) ──
    listIssues: "projects:listIssues",
  },
  providers: {
    create: "providers:create",
    delete: "providers:delete",
    detectInstalled: "providers:detectInstalled",
    disable: "providers:disable",
    enable: "providers:enable",
    getAccountInfo: "providers:getAccountInfo",
    getAll: "providers:getAll",
    getById: "providers:getById",
    getByKind: "providers:getByKind",
    getCommands: "providers:getCommands",
    getEnabled: "providers:getEnabled",
    getModels: "providers:getModels",
    getPlugins: "providers:getPlugins",
    getRateLimits: "providers:getRateLimits",
    getSkills: "providers:getSkills",
    installPlugin: "providers:installPlugin",
    readPlugin: "providers:readPlugin",
    uninstallPlugin: "providers:uninstallPlugin",
    update: "providers:update",
  },
  pulse: {
    create: "pulse:create",
    delete: "pulse:delete",
    getAll: "pulse:getAll",
    getById: "pulse:getById",
    runNow: "pulse:runNow",
    toggle: "pulse:toggle",
    update: "pulse:update",
  },
  runArtifacts: {
    add: "runArtifacts:add",
    getByRun: "runArtifacts:getByRun",
    remove: "runArtifacts:remove",
  },
  runContext: {
    add: "runContext:add",
    getByRun: "runContext:getByRun",
    remove: "runContext:remove",
  },
  runToolCalls: {
    getByRun: "runToolCalls:getByRun",
  },
  runTurns: {
    getByRun: "runTurns:getByRun",
  },
  runs: {
    abort: "runs:abort",
    archive: "runs:archive",
    canResume: "runs:canResume",
    cancel: "runs:cancel",
    complete: "runs:complete",
    continue: "runs:continue",
    create: "runs:create",
    delete: "runs:delete",
    deleteSession: "runs:deleteSession",
    diffUpdated: "runs:diffUpdated",
    ephemeralEvent: "runs:ephemeralEvent",
    eventPersisted: "runs:eventPersisted",
    execute: "runs:execute",
    executeReview: "runs:executeReview",
    fail: "runs:fail",
    fork: "runs:fork",
    getAll: "runs:getAll",
    getByAccount: "runs:getByAccount",
    getById: "runs:getById",
    getByStatus: "runs:getByStatus",
    getByWorkspace: "runs:getByWorkspace",
    getDetails: "runs:getDetails",
    start: "runs:start",
    statusChanged: "runs:statusChanged",
    toolApprovalRequest: "runs:toolApprovalRequest",
    toolApprovalResponse: "runs:toolApprovalResponse",
    update: "runs:update",
  },
  shell: {
    getAppsForFile: "shell:getAppsForFile",
    getInstalledApps: "shell:getInstalledApps",
    openExternal: "shell:openExternal",
    openFileWithBundle: "shell:openFileWithBundle",
    openInApp: "shell:openInApp",
    openPath: "shell:openPath",
  },
  signals: {
    create: "signals:create",
    delete: "signals:delete",
    getAll: "signals:getAll",
    getById: "signals:getById",
    update: "signals:update",
  },
  space: {
    archive: "space:archive",
    changed: "space:changed",
    create: "space:create",
    delete: "space:delete",
    getAll: "space:getAll",
    getById: "space:getById",
    unarchive: "space:unarchive",
    update: "space:update",
  },
  stats: {
    getDashboard: "stats:getDashboard",
  },
  sync: {
    runEntitySync: "sync:runEntitySync",
  },
  tasks: {
    create: "tasks:create",
    delete: "tasks:delete",
    getAll: "tasks:getAll",
    getById: "tasks:getById",
    update: "tasks:update",
  },
  terminal: {
    create: "terminal:create",
    data: "terminal:data",
    destroy: "terminal:destroy",
    resize: "terminal:resize",
    write: "terminal:write",
  },
  toolCalls: {
    complete: "toolCalls:complete",
    create: "toolCalls:create",
    fail: "toolCalls:fail",
    getByAccount: "toolCalls:getByAccount",
    getByRun: "toolCalls:getByRun",
    start: "toolCalls:start",
    update: "toolCalls:update",
  },
  updates: {
    check: "updates:check",
    download: "updates:download",
    getStatus: "updates:getStatus",
    quitAndInstall: "updates:quitAndInstall",
    status: "updates:status",
  },
  workspace: {
    // ── lifecycle ──
    archive: "workspace:archive",
    create: "workspace:create",
    delete: "workspace:delete",
    get: "workspace:get",
    getByRootPath: "workspace:getByRootPath",
    list: "workspace:list",
    listByAccount: "workspace:listByAccount",
    scriptComplete: "workspace:scriptComplete",
    selectDirectory: "workspace:selectDirectory",
    update: "workspace:update",
    // ── activity ──
    createActivity: "workspace:createActivity",
    createManyActivity: "workspace:createManyActivity",
    deleteActivity: "workspace:deleteActivity",
    listActivity: "workspace:listActivity",
    // ── diffs ──
    deleteLatestDiff: "workspace:deleteLatestDiff",
    getDiffByRun: "workspace:getDiffByRun",
    getLatestDiff: "workspace:getLatestDiff",
    getLatestDiffSummary: "workspace:getLatestDiffSummary",
    listDiffs: "workspace:listDiffs",
    // ── reviews ──
    createReview: "workspace:createReview",
    deleteReview: "workspace:deleteReview",
    getReview: "workspace:getReview",
    listReviews: "workspace:listReviews",
    updateReview: "workspace:updateReview",
    // ── findings ──
    createFinding: "workspace:createFinding",
    createManyFindings: "workspace:createManyFindings",
    deleteFinding: "workspace:deleteFinding",
    findingsChanged: "workspace:findingsChanged",
    getFinding: "workspace:getFinding",
    listFindings: "workspace:listFindings",
    listFindingsByWorkspace: "workspace:listFindingsByWorkspace",
    updateFinding: "workspace:updateFinding",
  },
} as const;
