// Single source of truth for IPC channel names.
//
// Main, preload, and renderer all reference values from this map instead of typing the
// channel string literally, so a typo at any site is a compile-time error and a renamed
// channel is a single edit. See CONTEXT.md for the IPC seam vocabulary.
export const CHANNELS = {
  account: {
    get: "account:get",
    update: "account:update",
  },
  app: {
    flushAndQuit: "app:flushAndQuit",
    fullscreenChange: "app:fullscreenChange",
    setMenuBarIconVisible: "app:setMenuBarIconVisible",
    setUnsavedChanges: "app:setUnsavedChanges",
  },
  appSettings: {
    get: "appSettings:get",
    update: "appSettings:update",
  },
  automations: {
    create: "automations:create",
    delete: "automations:delete",
    execute: "automations:execute",
    getAll: "automations:getAll",
    getAvailableActions: "automations:getAvailableActions",
    getById: "automations:getById",
    getRunHistory: "automations:getRunHistory",
    update: "automations:update",
  },
  browser: {
    attach: "browser:attach",
    back: "browser:back",
    deleteCapture: "browser:deleteCapture",
    destroy: "browser:destroy",
    detach: "browser:detach",
    forward: "browser:forward",
    getNavState: "browser:getNavState",
    navState: "browser:navState",
    navigate: "browser:navigate",
    reload: "browser:reload",
    selectModeChanged: "browser:selectModeChanged",
    selection: "browser:selection",
    setBounds: "browser:setBounds",
    setSelectMode: "browser:setSelectMode",
    setVisible: "browser:setVisible",
    stop: "browser:stop",
  },
  connectionStates: {
    getAll: "connectionStates:getAll",
    updateById: "connectionStates:updateById",
  },
  connections: {
    checkCredentials: "connections:checkCredentials",
    deleteResource: "connections:deleteResource",
    getAsanaProjects: "connections:getAsanaProjects",
    getByProvider: "connections:getByProvider",
    getGithubRepos: "connections:getGithubRepos",
    getGitlabProjects: "connections:getGitlabProjects",
    getJiraProjects: "connections:getJiraProjects",
    getLinearTeams: "connections:getLinearTeams",
    getSelectedResources: "connections:getSelectedResources",
    getSentryProjects: "connections:getSentryProjects",
    getSocketDevOrganizations: "connections:getSocketDevOrganizations",
    getTrelloBoards: "connections:getTrelloBoards",
    removeResource: "connections:removeResource",
    revoke: "connections:revoke",
    saveCredentials: "connections:saveCredentials",
    saveResources: "connections:saveResources",
  },
  entities: {
    create: "entities:create",
    delete: "entities:delete",
    getAll: "entities:getAll",
    getById: "entities:getById",
    search: "entities:search",
    update: "entities:update",
  },
  fileExplorer: {
    getPathInfo: "fileExplorer:getPathInfo",
    listDir: "fileExplorer:listDir",
    readDirectory: "fileExplorer:readDirectory",
    readDirectoryShallow: "fileExplorer:readDirectoryShallow",
    readFile: "fileExplorer:readFile",
    readFileText: "fileExplorer:readFileText",
    searchFiles: "fileExplorer:searchFiles",
  },
  git: {
    cloneRepo: "git:cloneRepo",
    createBranch: "git:createBranch",
    createWorktree: "git:createWorktree",
    getBranches: "git:getBranches",
    getCurrentBranch: "git:getCurrentBranch",
    getDiff: "git:getDiff",
    getLog: "git:getLog",
    getRemotes: "git:getRemotes",
    getRepoRoot: "git:getRepoRoot",
    getStatus: "git:getStatus",
    getWorktreesDir: "git:getWorktreesDir",
    importLocalRepo: "git:importLocalRepo",
    importLocalRepoDirect: "git:importLocalRepoDirect",
    initRepo: "git:initRepo",
    isRepo: "git:isRepo",
    removeWorktree: "git:removeWorktree",
    renameBranch: "git:renameBranch",
    resetHard: "git:resetHard",
  },
  guards: {
    checkPackage: "guards:checkPackage",
    checkPackages: "guards:checkPackages",
    getActiveGuard: "guards:getActiveGuard",
    getPackageScore: "guards:getPackageScore",
    scanWorkspace: "guards:scanWorkspace",
  },
  imageProxy: {
    sign: "imageProxy:sign",
  },
  issues: {
    create: "issues:create",
    delete: "issues:delete",
    getAll: "issues:getAll",
    getById: "issues:getById",
    update: "issues:update",
  },
  projectResources: {
    add: "projectResources:add",
    getAvailable: "projectResources:getAvailable",
    getByProject: "projectResources:getByProject",
    getIssues: "projectResources:getIssues",
    remove: "projectResources:remove",
  },
  projects: {
    archive: "projects:archive",
    create: "projects:create",
    delete: "projects:delete",
    findByRemoteOrigin: "projects:findByRemoteOrigin",
    findOrCreate: "projects:findOrCreate",
    getAll: "projects:getAll",
    getByAccount: "projects:getByAccount",
    getById: "projects:getById",
    remove: "projects:remove",
    update: "projects:update",
  },
  providers: {
    create: "providers:create",
    delete: "providers:delete",
    detectInstalled: "providers:detectInstalled",
    disable: "providers:disable",
    enable: "providers:enable",
    getAccountInfo: "providers:getAccountInfo",
    getAll: "providers:getAll",
    getById: "providers:getById",
    getByKind: "providers:getByKind",
    getCommands: "providers:getCommands",
    getEnabled: "providers:getEnabled",
    getModels: "providers:getModels",
    getPlugins: "providers:getPlugins",
    getRateLimits: "providers:getRateLimits",
    getSkills: "providers:getSkills",
    installPlugin: "providers:installPlugin",
    readPlugin: "providers:readPlugin",
    uninstallPlugin: "providers:uninstallPlugin",
    update: "providers:update",
  },
  pulse: {
    create: "pulse:create",
    delete: "pulse:delete",
    getAll: "pulse:getAll",
    getById: "pulse:getById",
    runNow: "pulse:runNow",
    toggle: "pulse:toggle",
    update: "pulse:update",
  },
  reviewFindings: {
    create: "reviewFindings:create",
    createMany: "reviewFindings:createMany",
    delete: "reviewFindings:delete",
    getById: "reviewFindings:getById",
    getByReview: "reviewFindings:getByReview",
    getByWorkspace: "reviewFindings:getByWorkspace",
    update: "reviewFindings:update",
  },
  reviews: {
    create: "reviews:create",
    delete: "reviews:delete",
    getById: "reviews:getById",
    getByWorkspace: "reviews:getByWorkspace",
    update: "reviews:update",
  },
  runArtifacts: {
    add: "runArtifacts:add",
    getByRun: "runArtifacts:getByRun",
    remove: "runArtifacts:remove",
  },
  runContext: {
    add: "runContext:add",
    getByRun: "runContext:getByRun",
    remove: "runContext:remove",
  },
  runToolCalls: {
    getByRun: "runToolCalls:getByRun",
  },
  runTurns: {
    getByRun: "runTurns:getByRun",
  },
  runs: {
    abort: "runs:abort",
    archive: "runs:archive",
    canResume: "runs:canResume",
    cancel: "runs:cancel",
    complete: "runs:complete",
    continue: "runs:continue",
    create: "runs:create",
    delete: "runs:delete",
    deleteSession: "runs:deleteSession",
    diffUpdated: "runs:diffUpdated",
    ephemeralEvent: "runs:ephemeralEvent",
    eventPersisted: "runs:eventPersisted",
    execute: "runs:execute",
    executeReview: "runs:executeReview",
    fail: "runs:fail",
    fork: "runs:fork",
    getAll: "runs:getAll",
    getByAccount: "runs:getByAccount",
    getById: "runs:getById",
    getByStatus: "runs:getByStatus",
    getByWorkspace: "runs:getByWorkspace",
    getDetails: "runs:getDetails",
    start: "runs:start",
    statusChanged: "runs:statusChanged",
    toolApprovalRequest: "runs:toolApprovalRequest",
    toolApprovalResponse: "runs:toolApprovalResponse",
    update: "runs:update",
  },
  seed: {
    accounts: "seed:accounts",
    all: "seed:all",
    connectionStates: "seed:connectionStates",
    connections: "seed:connections",
    providers: "seed:providers",
    spaces: "seed:spaces",
  },
  shell: {
    getAppsForFile: "shell:getAppsForFile",
    getInstalledApps: "shell:getInstalledApps",
    openExternal: "shell:openExternal",
    openFileWithBundle: "shell:openFileWithBundle",
    openInApp: "shell:openInApp",
    openPath: "shell:openPath",
  },
  signals: {
    create: "signals:create",
    delete: "signals:delete",
    getAll: "signals:getAll",
    getById: "signals:getById",
    update: "signals:update",
  },
  skillsMarketplace: {
    audit: "skillsMarketplace:audit",
    curated: "skillsMarketplace:curated",
    detail: "skillsMarketplace:detail",
    list: "skillsMarketplace:list",
    search: "skillsMarketplace:search",
  },
  space: {
    archive: "space:archive",
    changed: "space:changed",
    create: "space:create",
    delete: "space:delete",
    getAll: "space:getAll",
    getById: "space:getById",
    unarchive: "space:unarchive",
    update: "space:update",
  },
  stats: {
    getDashboard: "stats:getDashboard",
  },
  sync: {
    runEntitySync: "sync:runEntitySync",
  },
  tasks: {
    create: "tasks:create",
    delete: "tasks:delete",
    getAll: "tasks:getAll",
    getById: "tasks:getById",
    update: "tasks:update",
  },
  terminal: {
    create: "terminal:create",
    data: "terminal:data",
    destroy: "terminal:destroy",
    resize: "terminal:resize",
    write: "terminal:write",
  },
  toolCalls: {
    complete: "toolCalls:complete",
    create: "toolCalls:create",
    fail: "toolCalls:fail",
    getByAccount: "toolCalls:getByAccount",
    getByRun: "toolCalls:getByRun",
    start: "toolCalls:start",
    update: "toolCalls:update",
  },
  updates: {
    check: "updates:check",
    download: "updates:download",
    getStatus: "updates:getStatus",
    quitAndInstall: "updates:quitAndInstall",
    status: "updates:status",
  },
  workspaceActivity: {
    create: "workspaceActivity:create",
    createMany: "workspaceActivity:createMany",
    delete: "workspaceActivity:delete",
    getByWorkspace: "workspaceActivity:getByWorkspace",
  },
  workspaceDiffs: {
    deleteLatest: "workspaceDiffs:deleteLatest",
    getByRun: "workspaceDiffs:getByRun",
    getByWorkspace: "workspaceDiffs:getByWorkspace",
    getLatest: "workspaceDiffs:getLatest",
    getLatestSummary: "workspaceDiffs:getLatestSummary",
  },
  workspaces: {
    archive: "workspaces:archive",
    create: "workspaces:create",
    delete: "workspaces:delete",
    getAll: "workspaces:getAll",
    getByAccount: "workspaces:getByAccount",
    getById: "workspaces:getById",
    getByRootPath: "workspaces:getByRootPath",
    scriptComplete: "workspaces:scriptComplete",
    selectDirectory: "workspaces:selectDirectory",
    update: "workspaces:update",
  },
} as const;
