export const apps = [
  {
    id: "morning-summary",
    name: "Morning Summary",
    imageSrc: "/apps/morning-summary-skeuomorphic.png",
    imageAlt: "Morning Summary",
    highlighted: true,
  },
  // {
  //   id: "evening-summary",
  //   name: "Evening Summary",
  //   imageSrc: "/apps/evening-summary-skeuomorphic.png",
  //   imageAlt: "Evening Summary",
  //   highlighted: true,
  // },
  {
    id: "github",
    name: "GitHub",
    imageSrc: "/apps/github-skeuomorphic.png",
    imageAlt: "GitHub",
    highlighted: true,
  },
  {
    id: "apple-music",
    name: "Apple Music",
    imageSrc: "/apps/apple-music-skeuomorphic.png",
    imageAlt: "Apple Music",
  },
  // {
  //   id: "youtube",
  //   name: "YouTube",
  //   imageSrc: "/apps/youtube-skeuomorphic.png",
  //   imageAlt: "YouTube",
  // },
  {
    id: "raindrop",
    name: "Raindrop",
    imageSrc: "/apps/raindrop-skeuomorphic.png",
    imageAlt: "Raindrop",
  },
  // {
  //   id: "file-system",
  //   name: "File System",
  //   imageSrc: "/apps/file-system-skeuomorphic2.png",
  //   imageAlt: "File System",
  // },
  // {
  //   id: "obsidian",
  //   name: "Obsidian",
  //   imageSrc: "/apps/obsidian-skeuomorphic2.png",
  //   imageAlt: "Obsidian",
  // },
  {
    id: "podcast",
    name: "Podcast",
    imageSrc: "/apps/podcast-skeuomorphic.png",
    imageAlt: "Podcast",
  },
  {
    id: "spotify",
    name: "Spotify",
    imageSrc: "/apps/spotify-skeuomorphic.png",
    imageAlt: "Spotify",
  },
  {
    id: "hackernews",
    name: "Hacker News",
    imageSrc: "/apps/hackernews-skeuomorphic.png",
    imageAlt: "Hacker News",
    highlighted: true,
  },
  // {
  //   id: "goodreads",
  //   name: "Goodreads",
  //   imageSrc: "/apps/goodreads-skeuomorphic.png",
  //   imageAlt: "Goodreads",
  // },
  // {
  //   id: "linear",
  //   name: "Linear",
  //   imageSrc: "/apps/linear-skeuomorphic.png",
  //   imageAlt: "Linear",
  // },
  // {
  //   id: "notion",
  //   name: "Notion",
  //   imageSrc: "/apps/notion-skeuomorphic.png",
  //   imageAlt: "Notion",
  // },
  // {
  //   id: "jira",
  //   name: "Jira",
  //   imageSrc: "/apps/jira-skeuomorphic.png",
  //   imageAlt: "Jira",
  // },
  // {
  //   id: "x",
  //   name: "X (Twitter)",
  //   imageSrc: "/apps/x-skeuomorphic.png",
  //   imageAlt: "X (Twitter)",
  // },
  // {
  //   id: "apple-notes",
  //   name: "Apple Notes",
  //   imageSrc: "/apps/apple-notes-skeuomorphic.png",
  //   imageAlt: "Apple Notes",
  // },
  {
    id: "rss",
    name: "RSS",
    imageSrc: "/apps/rss-skeuomorphic.png",
    imageAlt: "RSS",
  },
  // {
  //   id: "thenewyorker",
  //   name: "The New Yorker",
  //   imageSrc: "/apps/thenewyorker-skeuomorphic.png",
  //   imageAlt: "The New Yorker",
  // },
  // {
  //   id: "aworkinglibrary",
  //   name: "A Working Library",
  //   imageSrc: "/apps/aworkinglibrary-skeuomorphic.png",
  //   imageAlt: "A Working Library",
  // },
  // {
  //   id: "safari",
  //   name: "Safari",
  //   imageSrc: "/apps/safari-skeuomorphic.png",
  //   imageAlt: "Safari",
  // },
  // {
  //   id: "apple-health",
  //   name: "Apple Health",
  //   imageSrc: "/apps/apple-health-skeuomorphic.png",
  //   imageAlt: "Apple Health",
  // },
  // {
  //   id: "calendar",
  //   name: "Calendar",
  //   imageSrc: "/apps/calendar-skeuomorphic.png",
  //   imageAlt: "Calendar",
  // },
  // {
  //   id: "mail",
  //   name: "Mail",
  //   imageSrc: "/apps/mail-skeuomorphic.png",
  //   imageAlt: "Mail",
  // },
  // {
  //   id: "photos",
  //   name: "Photos",
  //   imageSrc: "/apps/photos-skeuomorphic.png",
  //   imageAlt: "Photos",
  // },
  // {
  //   id: "birthday",
  //   name: "Birthday",
  //   imageSrc: "/apps/birthday-skeuomorphic.png",
  //   imageAlt: "Birthday",
  // },
  // {
  //   id: "weather",
  //   name: "Weather",
  //   imageSrc: "/apps/weather-skeuomorphic.png",
  //   imageAlt: "Weather",
  // },
  // {
  //   id: "reddit",
  //   name: "Reddit",
  //   imageSrc: "/apps/reddit-skeuomorphic.png",
  //   imageAlt: "Reddit",
  // },
  // {
  //   id: "instagram",
  //   name: "Instagram",
  //   imageSrc: "/apps/instagram-skeuomorphic.png",
  //   imageAlt: "Instagram",
  // },
];
