// ─────────────────────────────────────────────────────────────
// Provider Adapters Module
// ─────────────────────────────────────────────────────────────

// Types
export type {
  FileAttachment,
  WorkRunContextItem,
  WorkRunRequest,
  WorkRunContinueRequest,
  WorkRunForkRequest,
  WorkRunReviewTarget,
  WorkRunReviewRequest,
  WorkRunLogEvent,
  WorkRunToolCallEvent,
  WorkRunArtifactEvent,
  WorkRunStatusEvent,
  WorkRunSubagentEvent,
  WorkRunEvent,
  WorkRunArtifactSummary,
  StopReason,
  WorkRunResult,
  WorkRunEventHandler,
  WorkRunAdapter,
  CopilotAdapterConfig,
  ClaudeCodeAdapterConfig,
  ModelInfo,
  CommandInfo,
  SkillInfo,
  PluginListResponse,
  PluginInfo,
  MarketplaceInfo,
  CodexAccountInfo,
  PluginInterface,
  PluginDetail,
  PluginSkillSummary,
  PluginAppSummary,
  // Subagent types
  AgentModelOption,
  AgentDefinition,
  AgentsConfig,
  // Hook types
  HookEventName,
  HookInputBase,
  PreToolUseHookInput,
  PostToolUseHookInput,
  PostToolUseFailureHookInput,
  UserPromptSubmitHookInput,
  StopHookInput,
  SubagentStartHookInput,
  SubagentStopHookInput,
  PreCompactHookInput,
  PermissionRequestHookInput,
  SessionStartHookInput,
  SessionEndHookInput,
  NotificationHookInput,
  HookInput,
  HookContext,
  PreToolUseHookSpecificOutput,
  PostToolUseHookSpecificOutput,
  UserPromptSubmitHookSpecificOutput,
  SessionStartHookSpecificOutput,
  SubagentStartHookSpecificOutput,
  GenericHookSpecificOutput,
  HookSpecificOutput,
  HookOutput,
  HookCallback,
  HookMatcher,
  HooksConfig,
} from "./adapter.types";

// Factory
export {
  createWorkAdapter,
  getWorkAdapter,
  shutdownWorkAdapter,
  shutdownAllWorkAdapters,
  clearAdapterCache,
  invalidateWorkAdapter,
  isSupportedWorkProvider,
  listModelsForProvider,
  listCommandsForProvider,
  listSkillsForProvider,
  getAccountInfoForProvider,
  listPluginsForProvider,
  readPluginForProvider,
  installPluginForProvider,
  uninstallPluginForProvider,
  getRateLimitsForProvider,
  SUPPORTED_WORK_PROVIDERS,
  type SupportedWorkProvider,
} from "./adapter.factory";

// Adapters
export { createCopilotAdapter } from "./copilot.adapter";
export { createClaudeAdapter } from "./claude.adapter";
