export const CACHE_DEFAULTS = {
  EMBEDDING_MAX_SIZE: 500,
  EMBEDDING_TTL_MINUTES: 120,
  QUERY_MAX_SIZE: 100,
  QUERY_TTL_MINUTES: 30,
  RESPONSE_MAX_SIZE: 50,
  RESPONSE_TTL_MINUTES: 15,
} as const;
